### ISSUE TITLE
Onion Architecture

### ISSUE THREAD

**Issue by zsofitoth** [dancoconetu/DanBox#1]
- **BLL:** _Business Logic Layer_ (Class Library)
   - Interfaces (Folder)
   - Facades (Folder)
   - Providers (Folder)
   - Models (Folder)
- **DAL:** _Data Access Layer_ (Class Library)
  - Repositories (Folder)
- **SL:** _Service Layer_ (ASP.NET Core Web Application)
   - Controllers (Folder)
   - DTO (Folder) (_Data Transfer Objects_)
- **BLL.Tests** (xUnit)
- **SL.Tests** (xUnit)
- **DAL.Tests** (xUnit)

**Onion Architecture**
Everything references the BLL

**Design Patterns**
- _Facade_
[Design Patterns for Humans](https://github.com/kamranahmedse/design-patterns-for-humans#-facade)

- _Repository_
[Repository pattern with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/repository-pattern?view=aspnetcore-2.1)

- _Dependency Injection_
[Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1)

**Comment by dancoconetu** [comment]
Resolved!
