### ISSUE TITLE
Set up Swagger

### ISSUE THREAD

**Issue by zsofitoth** [dancoconetu/DanBox#7]
Use swagger to document the Web API and make testing the endpoints faster and easier.
[Swashbucke docs on MSDN](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml)

- Install swagger
- Set up to navigate to the swagger docs page on project startup

**Comment by dancoconetu** [comment]
Fixed with pull request #8
